# Generated by Django 3.1.2 on 2021-05-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('site', models.CharField(default='No title', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('text', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
