# Generated by Django 3.1.2 on 2021-05-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commnet_id',
            new_name='comment_id',
        ),
    ]
