# Generated by Django 3.1.2 on 2021-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site',
            field=models.CharField(default='No title', max_length=50),
        ),
    ]
